version: '3.7'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/modules:/var/www/html/modules:cached
      - ./web/profiles:/var/www/html/profiles:cached
      - ./web/themes:/var/www/html/themes:cached
      - ./web/sites:/var/www/html/sites:cached
    depends_on: 
      - db    

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: amoghe
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: Drupal8
    volumes:
        - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080



volumes:
  db_data:
